### ISSUE TITLE
Novice Struggling with finding dependencies

### ISSUE THREAD

**Issue by CMorrison82z** [spell-music/csound-expression#92] opened 2024-03-24 13:27 UTC
OS: EndeavourOS

Using `cabal repl` with:
`    build-depends:    base ^>=4.17.2.1
                    , csound-expression >= 5.4.3
                    , csound-catalog
`

installed `csound` and `WildMIDI` from the AUR. (Note I did NOT install cabal using AUR as that's known to cause issues)

I'm currently unable to get sound from `vdac midi`, and from temporal-media module (used in the "Scores" section). The virtual keyboard appears, but produces no sound

I suspect I'm missing some kind of dependency ?

**Comment by anton-k** [comment] 2024-06-12 16:57
Sorry for late reply this caused by this bug: #93 
I'm going to fix it in upcoming release.

**Comment by anton-k** [comment] 2024-06-12 16:58
I've tried vdac on new version and it works. Probably it was silenced by the bug in renderer.

**Comment by anton-k** [comment] 2024-06-16 16:38
It's fixed on master. I've uploded new version to hackage also.

**Closed** 2024-06-22 07:33 UTC
